name = 'ledgeranalysisreportingandprofiling'
pages_build_output_dir = "out"

[site]
bucket = "out"
compatibility_date = "2023-06-28"

[site.build]
command = "npm run build"
output_dir = "out"

[build]
command = "npm run build"